/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclient;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;


/**
 * @version 0.0.1
 * @author Rocchi Francesco
 */
public class GUI extends javax.swing.JFrame {
	private final ChatClient client;
	private final StyledDocument chatDocument;
	private final SimpleAttributeSet attributes;
	private String textToSend;
	private String selectedUser;
	private ArrayList<String> messages;
	private final JSONParser parser;
	private JSONObject root;

	/**
	 * Creates new form GUI
	 * @param client
	 */
	public GUI(ChatClient client) {
		this.client = client;
		parser = new JSONParser();
		initComponents();
		chatDocument = chatTextPane.getStyledDocument();
		attributes = new SimpleAttributeSet();
		chatTextPane.setParagraphAttributes(attributes, true);
		loginFrame.setVisible(true);
	}

	public String getSelectedUser() {
		return selectedUser;
	}

	public void setConversationsList(Vector users) {
		usersListPane.setListData(users);
	}
	
	//StyleConstants.setForeground(attributes, Color.RED);
	//StyleConstants.setBackground(attributes, Color.YELLOW);
	//StyleConstants.setAlignment(attributes, StyleConstants.ALIGN_RIGHT);
	//StyleConstants.setBold(attributes, true);
	
	public void printAsSender(String text) {
		try {
			StyleConstants.setAlignment(attributes, StyleConstants.ALIGN_RIGHT);
			chatDocument.insertString(chatDocument.getLength(), "Tu: " + text + "\n", attributes);
			textToSendField.setText("");
		} catch (BadLocationException ex) {
			Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	public void printAsAddressee(String text, String sender) {
		if(selectedUser != null && selectedUser.equals(sender)) {		// Significa che il 
			text = selectedUser + ": " + text + "\n";
			try {
				StyleConstants.setAlignment(attributes, StyleConstants.ALIGN_LEFT);
				chatDocument.insertString(chatDocument.getLength(), text, attributes);
			} catch (BadLocationException ex) {
				Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        usersListScrollPane = new javax.swing.JScrollPane();
        usersListPane = new javax.swing.JList();
        textToSendField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        chatTextScrollPane = new javax.swing.JScrollPane();
        chatTextPane = new javax.swing.JTextPane();
        searchUserButton = new javax.swing.JButton();
        searchUserTextField = new javax.swing.JTextField();

        loginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginFrame.setTitle("Login");
        loginFrame.setMinimumSize(new java.awt.Dimension(300, 200));
        loginFrame.setResizable(false);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField)
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(passwordField))
                .addContainerGap())
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usersListPane.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                usersListPaneValueChanged(evt);
            }
        });
        usersListScrollPane.setViewportView(usersListPane);

        textToSendField.setEnabled(false);
        textToSendField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textToSendFieldKeyPressed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.setEnabled(false);
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        chatTextPane.setEditable(false);
        chatTextScrollPane.setViewportView(chatTextPane);

        searchUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatclient/play.png"))); // NOI18N
        searchUserButton.setMinimumSize(new java.awt.Dimension(27, 27));
        searchUserButton.setPreferredSize(new java.awt.Dimension(27, 27));
        searchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserButtonActionPerformed(evt);
            }
        });

        searchUserTextField.setText("Cerca utente...");
        searchUserTextField.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchUserTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usersListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textToSendField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chatTextScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(usersListScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sendButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textToSendField)
                    .addComponent(searchUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchUserTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
		textToSend = textToSendField.getText();
		if(!textToSend.isEmpty() && selectedUser != null) {
			client.prepareAndSendMessage(textToSend);
			printAsSender(textToSend);
		}
	}//GEN-LAST:event_sendButtonActionPerformed

	private void usersListPaneValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_usersListPaneValueChanged
		selectedUser = (String) usersListPane.getSelectedValue();
		textToSendField.setEnabled(true);
		sendButton.setEnabled(true);
		chatTextPane.setText("");
		messages = client.getUsersAndMessages().get(selectedUser);
		for (String message : messages) {
			try {
				root = (JSONObject) parser.parse(message);
				if(root.get("addressee").equals(selectedUser))
					printAsSender((String) root.get("text"));
				else
					printAsAddressee((String) root.get("text"), selectedUser);
			} catch (ParseException ex) {
				Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}//GEN-LAST:event_usersListPaneValueChanged

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		String username = usernameField.getText();
		if(client.login(username, passwordField.getText())) {
			loginFrame.setVisible(false);
			this.setTitle("Chat di " + username);
			this.setVisible(true);
		} else
			JOptionPane.showMessageDialog(this, "Errore! Username o Password errati.", "USERNAME O PASSWORD ERRATI", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void textToSendFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textToSendFieldKeyPressed
		textToSend = textToSendField.getText();
		if(evt.getKeyCode() == KeyEvent.VK_ENTER && !textToSend.isEmpty()) {
			client.prepareAndSendMessage(textToSend);
			printAsSender(textToSend);
		}
    }//GEN-LAST:event_textToSendFieldKeyPressed

    private void searchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserButtonActionPerformed
		String userToSearch = searchUserTextField.getText();
		if(!userToSearch.isEmpty())
			client.searchUser(userToSearch);
    }//GEN-LAST:event_searchUserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane chatTextPane;
    private javax.swing.JScrollPane chatTextScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton searchUserButton;
    private javax.swing.JTextField searchUserTextField;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField textToSendField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JList usersListPane;
    private javax.swing.JScrollPane usersListScrollPane;
    // End of variables declaration//GEN-END:variables
}
